-- ============================================================================
-- SOUQ.GG — production seed data (25 products, 7 categories, 1 admin)
-- ============================================================================

-- ----- admin user (password = souq-admin-2026) -----------------------------
insert into profiles (id, email, password_hash, full_name, role, is_banned)
values (
  'a0000000-0000-0000-0000-000000000001',
  'admin@souq.gg',
  'scrypt$souqadmin2026salt$8249cddb902245b3652a224b457e465f0335dd83613654d70243dd96156117b1239ad782e58432169226ea569f612124651ade523073557212b521088400bbf0',
  'SOUQ Admin',
  'admin',
  false
)
on conflict (email) do update set role = 'admin';

-- ----- categories -----------------------------------------------------------
insert into categories (id, slug, name, description, icon, sort_order)
values
  ('c1111111-1111-1111-1111-111111111111', 'templates',   '{"en":"Templates","ar":"قوالب"}',       '{"en":"Notion, Word, Figma and design templates.","ar":"قوالب نوشن وورد وفيغما وتصميم."}',       'layout-template', 1),
  ('c2222222-2222-2222-2222-222222222222', 'spreadsheets','{"en":"Spreadsheets","ar":"شيتات"}',      '{"en":"Excel and Google Sheets — finance, planners, calculators.","ar":"إكسل وقوقل شيتس — مالية، مخططات، حواسب."}', 'table', 2),
  ('c3333333-3333-3333-3333-333333333333', 'prompts',     '{"en":"Prompts","ar":"برومبتات"}',      '{"en":"Curated prompt packs for ChatGPT, Claude, Gemini.","ar":"حزم برومبتات منسقة لـ ChatGPT و Claude و Gemini."}', 'sparkles', 3),
  ('c4444444-4444-4444-4444-444444444444', 'ebooks',      '{"en":"E-books","ar":"كتب رقمية"}',      '{"en":"Original guides and manuals authored by us.","ar":"أدلة ومراجع أصلية من تأليفنا."}', 'book-open', 4),
  ('c5555555-5555-5555-5555-555555555555', 'code',        '{"en":"Code","ar":"أكواد"}',            '{"en":"Snippets, scripts, and mini-projects.","ar":"مقاطع كود، سكربتات، ومشاريع صغيرة."}', 'code', 5),
  ('c6666666-6666-6666-6666-666666666666', 'notion',      '{"en":"Notion Systems","ar":"أنظمة نوشن"}','{"en":"Complete Notion workspaces and dashboards.","ar":"مساحات عمل نوشن ولوحات تحكم كاملة."}', 'database', 6),
  ('c7777777-7777-7777-7777-777777777777', 'courses',     '{"en":"Mini Courses","ar":"كورسات مصغرة"}',  '{"en":"Focused video courses under 90 minutes.","ar":"كورسات فيديو مركزة أقل من ٩٠ دقيقة."}', 'play-circle', 7)
on conflict (slug) do nothing;

-- ----- 25 products (mixed types, Arabic-first) ----------------------------
insert into products (id, slug, category_id, type, status, title, description_short, description_long, bullets, thumbnail_url, price_cents, compare_at_cents, currency, content_languages, license_type, download_limit, is_featured, sales_count, rating_avg, rating_count, published_at)
values
  ('p0000001-0000-0000-0000-000000000001','notion-second-brain',       'c6666666-6666-6666-6666-666666666666','notion','published','{"en":"Notion Second Brain","ar":"العقل الثاني — Notion"}','{"en":"All-in-one Notion system for capturing, organizing, and retrieving knowledge.","ar":"نظام Notion شامل لتسجيل وتنظيم واسترجاع المعرفة."}','{"en":"A complete PARA + Zettelkasten workspace built inside Notion. Capture ideas, organize projects, and retrieve knowledge in seconds. Includes 15 linked databases, 40+ templates, and a quickstart video.","ar":"مساحة عمل PARA + Zettelkasten كاملة داخل Notion. سجّل الأفكار، نظّم المشاريع، واسترجع المعرفة في ثوانٍ. تتضمن ١٥ قاعدة بيانات مترابطة، ٤٠+ قالب، وفيديو بدء سريع."}','[{"en":"15 linked databases","ar":"١٥ قاعدة بيانات مترابطة"},{"en":"PARA + Zettelkasten system","ar":"نظام PARA + Zettelkasten"},{"en":"40+ page templates","ar":"٤٠+ قالب صفحة"},{"en":"Quickstart video (Arabic + English)","ar":"فيديو البدء السريع (عربي + إنجليزي)"},{"en":"Lifetime updates","ar":"تحديثات مدى الحياة"}]','',2999,4999,'USD', ARRAY['en','ar'],'personal_use',5,true,342,4.82,48,now()),
  ('p0000002-0000-0000-0000-000000000002','saudi-sme-financial-model','c2222222-2222-2222-2222-222222222222','excel','published','{"en":"Saudi SME Financial Model","ar":"نموذج مالي — شركات صغيرة سعودية"}','{"en":"Investor-ready Excel model for Saudi startups and SMEs.","ar":"نموذج Excel جاهز للمستثمرين لشركات ناشئة وصغيرة في السعودية."}','{"en":"Built specifically for Saudi market — includes revenue projections, P&L, balance sheet, cash flow, cap table, valuation, and Zakat calculation. Fully formula-driven with tutorial notes in every sheet.","ar":"مبني خصيصاً للسوق السعودي — يتضمن توقعات الإيرادات، الأرباح والخسائر، الميزانية العمومية، التدفق النقدي، جدول الملكية، التقييم، وحساب الزكاة. كل المعادلات مدفوعة بالصيغ مع ملاحظات تعليمية في كل شيت."}','[{"en":"3-year projections","ar":"توقعات ثلاث سنوات"},{"en":"P&L + Balance Sheet + Cash Flow","ar":"أرباح وخسائر + ميزانية عمومية + تدفق نقدي"},{"en":"Cap Table + Valuation","ar":"جدول ملكية + تقييم"},{"en":"Zakat-ready calculations","ar":"حسابات جاهزة للزكاة"},{"en":"Tutorial notes in every sheet","ar":"ملاحظات توضيحية في كل شيت"}]','',5999,9999,'USD', ARRAY['en','ar'],'business_use',5,true,215,4.75,31,now()),
  ('p0000003-0000-0000-0000-000000000003','chatgpt-arabic-marketing','c3333333-3333-3333-3333-333333333333','prompt_pack','published','{"en":"ChatGPT Arabic Marketing Pack","ar":"حزمة تسويق عربي — ChatGPT"}','{"en":"250+ battle-tested Arabic marketing prompts.","ar":"٢٥٠+ برومبت تسويق عربي مجربة."}','{"en":"Copywriters and social media managers in the Gulf use these prompts daily. Covers ad copy, email sequences, Instagram captions, LinkedIn posts, landing pages, and SEO meta descriptions — all in native Arabic with dialect options.","ar":"يستخدم هؤلاء الناسخون ومديرو التواصل الاجتماعي في الخليج هذه البرومبتات يومياً. تغطي نصوص الإعلانات، سلاسل البريد، كابشنات إنستقرام، منشورات لينكدإن، صفحات الهبوط، ووصف SEO — كلها بالعربية الفصحى مع خيارات لهجاتية."}','[{"en":"250+ prompts","ar":"٢٥٠+ برومبت"},{"en":"Ad copy + email + social","ar":"إعلانات + بريد + سوشل"},{"en":"SEO meta descriptions","ar":"أوصاف SEO"},{"en":"Dialect-aware Arabic","ar":"عربية واعية باللهجات"},{"en":"Sorted by use case","ar":"مرتبة حسب الاستخدام"}]','',1499,2499,'USD', ARRAY['en','ar'],'commercial_use',5,false,528,4.68,72,now()),
  ('p0000004-0000-0000-0000-000000000004','gulf-hr-policy-handbook','c1111111-1111-1111-1111-111111111111','pdf','published','{"en":"Gulf HR Policy Handbook","ar":"دليل سياسات الموارد البشرية — الخليج"}','{"en":"Complete HR policy template compliant with GCC labor laws.","ar":"قالب سياسات موارد بشرية كامل متوافق مع قوانين العمل الخليجية."}','{"en":"A 90-page handbook covering recruitment, onboarding, leave policies, performance management, termination procedures, and remote-work guidelines. Written by a certified GCC HR consultant and reviewed by a Saudi labor lawyer.","ar":"دليل ٩٠ صفحة يغطي التوظيف، الانضمام، سياسات الإجازة، إدارة الأداء، إجراءات إنهاء الخدمة، وإرشادات العمل عن بُعد. مكتوب من قِبل مستشار موارد بشرية معتمد في الخليج ومراجع من قِبل محامي سعودي مختص."}','[{"en":"90 pages, editable Word + PDF","ar":"٩٠ صفحة، Word + PDF قابلين للتعديل"},{"en":"GCC compliant","ar":"متوافق مع قوانين الخليج"},{"en":"Recruitment to termination","ar":"من التوظيف حتى إنهاء الخدمة"},{"en":"Remote work addendum","ar":"ملحق العمل عن بُعد"},{"en":"Arabic + English side-by-side","ar":"عربي + إنجليزي جنباً إلى جنب"}]','',4999,7999,'USD', ARRAY['en','ar'],'business_use',5,true,128,4.91,14,now()),
  ('p0000005-0000-0000-0000-000000000005','ecommerce-kit-notion','c6666666-6666-6666-6666-666666666666','notion','published','{"en":"E-commerce Kit — Notion","ar":"طقم التجارة الإلكترونية — Notion"}','{"en":"Run your e-commerce business from one Notion dashboard.","ar":"أدر تجارتك الإلكترونية من لوحة Notion واحدة."}','{"en":"Track inventory, suppliers, orders, customers, finances, and marketing campaigns in a single Notion workspace. Built for Shopify, WooCommerce, and Instagram sellers in the Gulf. Includes automation recipes and Zapier templates.","ar":"تتبع المخزون، الموردين، الطلبات، العملاء، المالية، والحملات التسويقية في مساحة عمل Notion واحدة. مبني لبائعي Shopify وWooCommerce وإنستقرام في الخليج. تتضمن وصفات أتمتة وقالب Zapier."}','[{"en":"Inventory + orders + CRM","ar":"مخزون + طلبات + CRM"},{"en":"Suppliers database","ar":"قاعدة بيانات الموردين"},{"en":"Finance tracker","ar":"متتبع المالية"},{"en":"Marketing campaign board","ar":"لوحة الحملات التسويقية"},{"en":"Zapier automations included","ar":"أتمتات Zapier مرفقة"}]','',2499,3999,'USD', ARRAY['en','ar'],'commercial_use',5,false,89,4.55,22,now()),
  ('p0000006-0000-0000-0000-000000000006','notion-ultimate-life-planner','c6666666-6666-6666-6666-666666666666','notion','published','{"en":"Ultimate Life Planner — Notion","ar":"مخطط الحياة الشامل — Notion"}','{"en":"Plan your goals, habits, and daily tasks with this all-in-one Notion workspace.","ar":"خطط لأهدافك، عاداتك، ومهامك اليومية مع مساحة العمل الشاملة هذه في Notion."}','{"en":"Inspired by the Getting Things Done methodology, this planner combines yearly goals, quarterly reviews, habit trackers, project roadmaps, and daily journaling. Designed for busy professionals who want clarity without complexity.","ar":"مستوحى من منهجية Getting Things Done، يجمع هذا المخطط بين الأهداف السنوية، المراجعات الفصلية، متتبعات العادات، خرائط المشاريع، والتدوين اليومي. مصمم للمحترفين المشغولين الذين يريدون وضوحاً دون تعقيد."}','[{"en":"Yearly + quarterly + monthly views","ar":"عرض سنوي + فصلي + شهري"},{"en":"Habit tracker with streaks","ar":"متتبع العادات مع سلاسل"},{"en":"Project roadmap","ar":"خريطة مشروع"},{"en":"Daily journaling template","ar":"قالب التدوين اليومي"},{"en":"GTD-inspired workflow","ar":"سير عمل مستوحى من GTD"}]','',1999,3499,'USD', ARRAY['en','ar'],'personal_use',5,false,156,4.71,29,now()),
  ('p0000007-0000-0000-0000-000000000007','gulf-content-calendar-2026','c2222222-2222-2222-2222-222222222222','excel','published','{"en":"Gulf Content Calendar 2026","ar":"رزنامة المحتوى ٢٠٢٦ — الخليج"}','{"en":"A full-year content calendar tailored for Gulf influencers and brands.","ar":"رزنامة محتوى للعام الكامل مخصصة لمؤثرين وعلامات تجارية في الخليج."}','{"en":"52 weeks of content themes, posting schedules, hashtag sets, and campaign slots aligned with Saudi and UAE holidays (Founding Day, Eid, Ramadan, National Day, Black Friday). Includes an AI prompt companion for every week.","ar":"٥٢ أسبوعاً من مواضيع المحتوى، جداول النشر، مجموعات الهاشتاق، ومواعيد الحملات المتوافقة مع إجازات السعودية والإمارات (يوم التأسيس، العيد، رمضان، اليوم الوطني، الجمعة السوداء). تتضمن رفيق برومبت AI لكل أسبوع."}','[{"en":"52 weeks pre-filled","ar":"٥٢ أسبوعاً مُعبأ مسبقاً"},{"en":"Saudi + UAE holiday slots","ar":"فترات الإجازات السعودية + الإماراتية"},{"en":"Hashtag sets per week","ar":"مجموعات هاشتاق أسبوعية"},{"en":"Campaign planning tabs","ar":"تبويبات تخطيط الحملات"},{"en":"AI prompt companion","ar":"رفيق برومبت AI"}]','',1999,2999,'USD', ARRAY['en','ar'],'commercial_use',5,false,67,4.62,13,now()),
  ('p0000008-0000-0000-0000-000000000008','python-web-scraper-starter','c5555555-5555-5555-5555-555555555555','code','published','{"en":"Python Web Scraper Starter","ar":"بداية سكربت بايثون للتحليل"}','{"en":"Production-ready Python scraper with proxy rotation, retry logic, and data export.","ar":"سكربت بايثون جاهز للإنتاج مع تدوير بروكسي، منطق إعادة المحاولة، وتصدير البيانات."}','{"en":"Built for e-commerce intelligence, lead generation, and price monitoring. Includes async requests via aiohttp, BeautifulSoup parsing, rotating proxy support, SQLite caching, and export to CSV/JSON/Excel. Fully commented in Arabic and English.","ar":"مبني لذكاء التجارة الإلكترونية، توليد العملاء المحتملين، ومراقبة الأسعار. يتضمن طلبات async عبر aiohttp، تحليل BeautifulSoup، دعم بروكسي متدوّر، تخزين مؤقت SQLite، وتصدير إلى CSV/JSON/Excel. مُعلق بالكامل بالعربية والإنجليزية."}','[{"en":"Async aiohttp requests","ar":"طلبات aiohttp async"},{"en":"BeautifulSoup + CSS selectors","ar":"BeautifulSoup + محددات CSS"},{"en":"Rotating proxy support","ar":"دعم بروكسي متدوّر"},{"en":"SQLite caching layer","ar":"طبقة تخزين مؤقت SQLite"},{"en":"Export CSV/JSON/Excel","ar":"تصدير CSV/JSON/Excel"}]','',1499,2499,'USD', ARRAY['en','ar'],'commercial_use',5,false,203,4.78,41,now()),
  ('p0000009-0000-0000-0000-000000000009','brand-identity-kit-figma','c1111111-1111-1111-1111-111111111111','template','published','{"en":"Brand Identity Kit — Figma","ar":"طقم هوية العلامة التجارية — Figma"}','{"en":"Complete Figma brand kit with logo variations, color system, typography, and social templates.","ar":"طقم Figma شاملة مع متغيرات الشعار، نظام الألوان، الطباعة، وقوالب التواصل."}','{"en":"Designed for startups and agencies in MENA. Includes logo grid, primary and secondary colors with hex codes, font pairings for Arabic and English, Instagram story/post templates, business card mockup, and a brand guidelines page. Everything is editable in Figma with auto-layout.","ar":"مصمم للشركات الناشئة والوكالات في الشرق الأوسط وشمال إفريقيا. يتضمن شبكة الشعار، الألوان الأساسية والثانوية مع أكواد hex، أزواج الخطوط العربية والإنجليزية، قوالب ستوري/بوست إنستقرام، نموذج بطاقة أعمال، وصفحة إرشادات العلامة. كل شيء قابل للتعديل في Figma مع auto-layout."}','[{"en":"Logo grid + variations","ar":"شبكة الشعار + المتغيرات"},{"en":"Arabic + English font pairings","ar":"أزواج خطوط عربية + إنجليزية"},{"en":"Instagram story + post templates","ar":"قوالب ستوري + بوست إنستقرام"},{"en":"Business card mockup","ar":"نموذج بطاقة أعمال"},{"en":"Brand guidelines page","ar":"صفحة إرشادات العلامة"}]','',3499,5499,'USD', ARRAY['en','ar'],'commercial_use',5,true,94,4.85,17,now()),
  ('p0000010-0000-0000-0000-000000000010','midjourney-architecture-prompts','c3333333-3333-3333-3333-333333333333','prompt_pack','published','{"en":"Midjourney Architecture Prompts","ar":"برومبتات معمارية — Midjourney"}','{"en":"150 prompts to generate architectural renders, interiors, and landscape concepts.","ar":"١٥٠ برومبت لتوليد رسومات معمارية، داخليات، ومفاهيم مناظر طبيعية."}','{"en":"Created by an architect who uses Midjourney daily for client presentations. Includes styles from Zaha Hadid to traditional Arabic courtyard houses. Each prompt comes with parameter variations, aspect ratio recommendations, and example outputs.","ar":"مُنشأة من قِبل مهندس معماري يستخدم Midjourney يومياً للعروض التقديمية للعملاء. تتضمن أنماطاً من زها حديد إلى المنازل العربية التقليدية ذات الفناء. كل برومبت يأتي مع متغيرات المعاملات، توصيات نسبة العرض، ومخرجات مثالية."}','[{"en":"150 architecture prompts","ar":"١٥٠ برومبت معماري"},{"en":"Interior + exterior + landscape","ar":"داخلي + خارجي + مناظر طبيعية"},{"en":"Style variations included","ar":"متغيرات الأنماط مرفقة"},{"en":"Parameter + aspect ratio guide","ar":"دليل المعاملات + نسبة العرض"},{"en":"Example outputs gallery","ar":"معرض المخرجات المثالية"}]','',1299,1999,'USD', ARRAY['en','ar'],'personal_use',5,false,312,4.69,55,now()),
  ('p0000011-0000-0000-0000-000000000011','freelance-contract-template-ar','c1111111-1111-1111-1111-111111111111','word','published','{"en":"Freelance Contract Template (AR)","ar":"نموذج عقد مستقل (عربي)"}','{"en":"Legally-informed Arabic freelance contract template reviewed by a GCC lawyer.","ar":"قالب عقد مستقل عربي مُستنبت قانونياً ومراجع من قِبل محامٍ خليجي."}','{"en":"Covers scope of work, payment terms, milestone schedule, intellectual property transfer, revision limits, late payment penalties, and termination clauses. Written in formal Arabic ( fus.ha ) with side-by-side English annotations for international clients.","ar":"يغطي نطاق العمل، شروط الدفع، جدول الملفات، نقل الملكية الفكرية، حدود المراجعة، عقوبات التأخير، وبنود إنهاء الخدمة. مكتوب بالعربية الفصحى مع تعليقات إنجليزية جنباً إلى جنب للعملاء الدوليين."}','[{"en":"Scope + payment + milestones","ar":"النطاق + الدفع + الملفات"},{"en":"IP transfer clause","ar":"بند نقل الملكية الفكرية"},{"en":"Late payment penalties","ar":"عقوبات التأخير في الدفع"},{"en":"Termination clauses","ar":"بنود إنهاء الخدمة"},{"en":"Arabic + English annotations","ar":"تعليقات عربية + إنجليزية"}]','',999,1499,'USD', ARRAY['en','ar'],'commercial_use',5,false,418,4.73,62,now()),
  ('p0000012-0000-0000-0000-000000000012','saram-dashboard-excel','c2222222-2222-2222-2222-222222222222','excel','published','{"en":"SARAM Dashboard — Excel","ar":"لوحة SARAM — Excel"}','{"en":"Track your Saudi personal investments, Zakat, and net worth in one Excel dashboard.","ar":"تتبع استثماراتك الشخصية السعودية، زكاتك، وثروتك الصافية في لوحة Excel واحدة."}','{"en":"Built for Saudi residents who invest in stocks, real estate, and crypto. Automatically calculates Zakat on tradable assets using the Nisab threshold from SAMA. Includes portfolio allocation charts, dividend tracker, and capital gains log.","ar":"مبني لمقيمي السعودية الذين يستثمرون في الأسهم، العقارات، والعملات الرقمية. يحسب الزكاة تلقائياً على الأصول القابلة للتداول باستخدام عتبة النصاب من SAMA. يتضمن رسوم تخصيص المحفظة، متتبع الأرباح، وسجل الأرباح الرأسمالية."}','[{"en":"Zakat auto-calculation (SAMA Nisab)","ar":"حساب الزكاة التلقائي (نصاب SAMA)"},{"en":"Stocks + real estate + crypto","ar":"أسهم + عقارات + عملات رقمية"},{"en":"Portfolio allocation charts","ar":"رسوم تخصيص المحفظة"},{"en":"Dividend tracker","ar":"متتبع الأرباح"},{"en":"Capital gains log","ar":"سجل الأرباح الرأسمالية"}]','',3999,5999,'USD', ARRAY['en','ar'],'personal_use',5,true,176,4.88,24,now()),
  ('p0000013-0000-0000-0000-000000000013','social-media-report-template','c1111111-1111-1111-1111-111111111111','template','published','{"en":"Social Media Report Template","ar":"قالب تقرير التواصل الاجتماعي"}','{"en":"Client-ready social media report in PowerPoint + Google Slides.","ar":"تقرير التواصل الاجتماعي الجاهز للعميل في PowerPoint + Google Slides."}','{"en":"Designed for social media managers and agencies. Covers growth metrics, engagement analysis, top-performing content, audience demographics, competitor benchmark, and next-month recommendations. Fully editable charts and Arabic/English layout.","ar":"مصمم لمديري التواصل الاجتماعي والوكالات. يغطي مؤشرات النمو، تحليل المشاركة، أفضل المحتوى أداءً، ديموغرافيا الجمهور، معيار المنافسين، وتوصيات الشهر القادم. رسوم قابلة للتعديل بالكامل وتخطيط عربي/إنجليزي."}','[{"en":"Growth + engagement metrics","ar":"مؤشرات النمو + المشاركة"},{"en":"Top-performing posts","ar":"أفضل المنشورات أداءً"},{"en":"Audience demographics","ar":"ديموغرافيا الجمهور"},{"en":"Competitor benchmark","ar":"معيار المنافسين"},{"en":"Monthly recommendations slide","ar":"شريحة توصيات شهرية"}]','',1499,2499,'USD', ARRAY['en','ar'],'commercial_use',5,false,83,4.60,15,now()),
  ('p0000014-0000-0000-0000-000000000014','email-marketing-swipe-file','c4444444-4444-4444-4444-444444444444','pdf','published','{"en":"Email Marketing Swipe File","ar":"ملف البريد التسويقي الجاهز"}','{"en":"100 high-converting email templates for e-commerce and SaaS.","ar":"١٠٠ قالب بريد إلكتروني عالي التحويل للتجارة الإلكترونية وSaaS."}','{"en":"Written by a copywriter who sold $2M+ of digital products via email. Covers welcome sequences, product launches, cart abandonment, win-back campaigns, flash sales, and post-purchase upsells. Each template includes subject lines, preheaders, and psychological triggers.","ar":"مكتوب من قِبل ناسخ باع منتجات رقمية بأكثر من ٢ مليون دولار عبر البريد. يغطي سلاسل الترحيب، إطلاق المنتجات، تخلي عن السلة، حملات الاستعادة، المبيعات السريعة، والمبيعات الإضافية بعد الشراء. كل قالب يتضمن أسطر الموضوع، الرؤوس المسبقة، والمحفزات النفسية."}','[{"en":"100 email templates","ar":"١٠٠ قالب بريد"},{"en":"Welcome + launch + abandonment","ar":"ترحيب + إطلاق + تخلي"},{"en":"Subject lines + preheaders","ar":"أسطر الموضوع + الرؤوس المسبقة"},{"en":"Psychological triggers explained","ar":"محفزات نفسية موضحة"},{"en":"Arabic + English versions","ar":"نسخ عربية + إنجليزية"}]','',2499,3999,'USD', ARRAY['en','ar'],'commercial_use',5,true,291,4.81,38,now()),
  ('p0000015-0000-0000-0000-000000000015','notion-job-tracker','c6666666-6666-6666-6666-666666666666','notion','published','{"en":"Job Tracker — Notion","ar":"متتبع الوظائف — Notion"}','{"en":"Organize your job search with this Notion database and pipeline system.","ar":"نظم بحثك عن الوظيفة مع قاعدة بيانات Notion ونظام المجرى."}','{"en":"Track applications, interviews, follow-ups, and offers in one view. Includes a company research template, salary negotiation checklist, interview question library, and a dashboard that shows conversion rates at each stage. Built for new grads and career switchers in the Gulf.","ar":"تتبع الطلبات، المقابلات، المتابعات، والعروض في عرض واحد. يتضمن قالب بحث شركة، قائمة مراجعة تفاوض الراتب، مكتبة أسئلة المقابلة، ولوحة تحكم تعرض معدلات التحويل في كل مرحلة. مبني للخريجين الجدد ومحوّلي المسارات المهنية في الخليج."}','[{"en":"Application pipeline board","ar":"لوحة مجرى الطلبات"},{"en":"Interview question library","ar":"مكتبة أسئلة المقابلة"},{"en":"Salary negotiation checklist","ar":"قائمة مراجعة تفاوض الراتب"},{"en":"Company research template","ar":"قالب بحث الشركة"},{"en":"Conversion rate dashboard","ar":"لوحة معدلات التحويل"}]','',999,1499,'USD', ARRAY['en','ar'],'personal_use',5,false,134,4.67,21,now()),
  ('p0000016-0000-0000-0000-000000000016','arabic-copywriting-formula-guide','c4444444-4444-4444-4444-444444444444','pdf','published','{"en":"Arabic Copywriting Formula Guide","ar":"دليل صياغة النصوص العربية"}','{"en":"The definitive guide to writing persuasive Arabic copy for ads, landing pages, and emails.","ar":"الدليل النهائي لكتابة نصوص عربية مقنعة للإعلانات، صفحات الهبوط، والبريد."}','{"en":"Covers PAS, AIDA, BAB, FAB, and 4U frameworks adapted for Arabic rhetoric. Includes before/after rewrites of real Gulf ads, headline formulas, CTA templates, and a 50-point copy audit checklist.","ar":"يغطي إطارات PAS وAIDA وBAB وFAB و4U المُكيّفة للبلاغة العربية. يتضمن إعادة كتابة قبل/بعد لإعلانات خليجية حقيقية، صيغ عناوين، قوالب CTA، وقائمة مراجعة تدقيق نصي من ٥٠ نقطة."}','[{"en":"PAS + AIDA + BAB + FAB + 4U","ar":"PAS + AIDA + BAB + FAB + 4U"},{"en":"Before/after rewrites","ar":"إعادة كتابة قبل/بعد"},{"en":"Headline formulas","ar":"صيغ العناوين"},{"en":"CTA templates","ar":"قوالب CTA"},{"en":"50-point copy audit","ar":"تدقيق نصي من ٥٠ نقطة"}]','',1999,2999,'USD', ARRAY['en','ar'],'commercial_use',5,false,247,4.74,43,now()),
  ('p0000017-0000-0000-0000-000000000017','react-admin-dashboard-kit','c5555555-5555-5555-5555-555555555555','code','published','{"en":"React Admin Dashboard Kit","ar":"طقم لوحة تحكم React"}','{"en":"Production-ready React admin dashboard with auth, charts, tables, and dark mode.","ar":"لوحة تحكم React جاهزة للإنتاج مع مصادقة، رسوم بيانية، جداول، ووضع داكن."}','{"en":"Built with Next.js 14, Tailwind CSS, and shadcn/ui. Includes authentication middleware, role-based access, data table with sorting/filtering/pagination, recharts integration, a settings page, and a responsive sidebar. TypeScript strict, fully typed, zero any.","ar":"مبني مع Next.js 14 وTailwind CSS وshadcn/ui. يتضمن middleware مصادقة، وصول قائم على الأدوار، جدول بيانات مع ترتيب/تصفية/تقسيم، تكامل recharts، صفحة إعدادات، وشريط جانبي متجاوب. TypeScript strict، مكتوب بالكامل، بدون any."}','[{"en":"Next.js 14 + Tailwind + shadcn/ui","ar":"Next.js 14 + Tailwind + shadcn/ui"},{"en":"Auth + RBAC middleware","ar":"Auth + RBAC middleware"},{"en":"Data table with sort/filter/paginate","ar":"جدول بيانات مع فرز/تصفية/تقسيم"},{"en":"Recharts integration","ar":"تكامل Recharts"},{"en":"Dark mode + responsive","ar":"وضع داكن + متجاوب"}]','',4999,8999,'USD', ARRAY['en','ar'],'commercial_use',5,false,56,4.52,11,now()),
  ('p0000018-0000-0000-0000-000000000018','podcast-launch-playbook','c4444444-4444-4444-4444-444444444444','pdf','published','{"en":"Podcast Launch Playbook","ar":"دليل إطلاق البودكاست"}','{"en":"Launch your Arabic podcast from zero to first episode in 30 days.","ar":"أطلق بودكاستك العربي من الصفر إلى الحلقة الأولى في ٣٠ يوماً."}','{"en":"A step-by-step playbook covering niche selection, branding, equipment recommendations, recording workflow, editing checklists, hosting platform comparison, distribution to Apple Podcasts/Spotify/Anghami, and a launch marketing checklist.","ar":"دليل خطوة بخطوة يغطي اختيار المجال، بناء العلامة، توصيات المعدات، سير عمل التسجيل، قوائم مراجعة التعديل، مقارنة منصات الاستضافة، التوزيع على Apple Podcasts/Spotify/Anghami، وقائمة مراجعة تسويق الإطلاق."}','[{"en":"30-day roadmap","ar":"خريطة ٣٠ يوماً"},{"en":"Equipment recommendations","ar":"توصيات المعدات"},{"en":"Recording + editing workflow","ar":"سير عمل التسجيل + التعديل"},{"en":"Distribution guide","ar":"دليل التوزيع"},{"en":"Launch marketing checklist","ar":"قائمة مراجعة تسويق الإطلاق"}]','',1499,2499,'USD', ARRAY['en','ar'],'personal_use',5,false,189,4.79,33,now()),
  ('p0000019-0000-0000-0000-000000000019','linkedin-personal-brand-kit','c1111111-1111-1111-1111-111111111111','template','published','{"en":"LinkedIn Personal Brand Kit","ar":"طقم العلامة الشخصية — LinkedIn"}','{"en":"Systematically grow your LinkedIn presence with templates, calendars, and analytics.","ar":"نمِّي حضورك على LinkedIn بشكل منهجي مع قوالب، تقاويم، وتحليلات."}','{"en":"Includes a 90-day content calendar, 50 post templates (thought leadership, carousel, personal story, industry trends), profile optimization checklist, connection request scripts, and a weekly analytics tracker. Built for consultants, founders, and job seekers in MENA.","ar":"يتضمن تقويم محتوى لـ ٩٠ يوماً، ٥٠ قالب منشور (قيادة فكرية، سلسلة صور، قصة شخصية، اتجاهات الصناعة)، قائمة مراجعة تحسين الملف، نصوص طلبات التواصل، ومتتبع تحليلات أسبوعي. مبني للمستشارين، المؤسسين، والباحثين عن وظيفة في منطقة الشرق الأوسط وشمال إفريقيا."}','[{"en":"90-day content calendar","ar":"تقويم محتوى ٩٠ يوماً"},{"en":"50 post templates","ar":"٥٠ قالب منشور"},{"en":"Profile optimization checklist","ar":"قائمة مراجعة تحسين الملف"},{"en":"Connection request scripts","ar":"نصوص طلبات التواصل"},{"en":"Weekly analytics tracker","ar":"متتبع تحليلات أسبوعي"}]','',1999,3499,'USD', ARRAY['en','ar'],'commercial_use',5,false,112,4.64,19,now()),
  ('p0000020-0000-0000-0000-000000000020','seo-arabic-keyword-research-pack','c3333333-3333-3333-3333-333333333333','dataset','published','{"en":"Arabic SEO Keyword Research Pack","ar":"حزمة بحث كلمات مفتاحية عربية — SEO"}','{"en":"50,000 Arabic keywords with search volume, difficulty, and CPC for Saudi and UAE markets.","ar":"٥٠,٠٠٠ كلمة مفتاحية عربية مع حجم البحث، الصعوبة، وCPC لأسواق السعودية والإمارات."}','{"en":"Cleaned, deduplicated, and categorized by industry (finance, health, education, real estate, e-commerce, travel, food). Includes long-tail suggestions, question keywords, and competitor gap analysis framework. Delivered as CSV + Notion database.","ar":"مُنظفة، مُزالة التكرار، ومُصنفة حسب الصناعة (المالية، الصحة، التعليم، العقارات، التجارة الإلكترونية، السفر، الطعام). تتضمن اقتراحات الذيل الطويل، كلمات السؤال، وإطار تحليل فجوة المنافسين. مُسلمة كـ CSV + قاعدة بيانات Notion."}','[{"en":"50,000 keywords (Saudi + UAE)","ar":"٥٠,٠٠٠ كلمة مفتاحية (سعودية + إماراتية)"},{"en":"Search volume + difficulty + CPC","ar":"حجم البحث + الصعوبة + CPC"},{"en":"7 industry categories","ar":"٧ فئات صناعية"},{"en":"Long-tail + question keywords","ar":"ذيل طويل + كلمات سؤال"},{"en":"CSV + Notion format","ar":"CSV + Notion"}]','',2999,4999,'USD', ARRAY['en','ar'],'commercial_use',5,false,78,4.71,14,now()),
  ('p0000021-0000-0000-0000-000000000021','ramadan-marketing-campaign-kit','c1111111-1111-1111-1111-111111111111','template','published','{"en":"Ramadan Marketing Campaign Kit","ar":"طقم حملة تسويق رمضان"}','{"en":"Everything you need to run a Ramadan marketing campaign in the Gulf.","ar":"كل ما تحتاجه لتنفيذ حملة تسويقية في رمضان في الخليج."}','{"en":"Includes a 30-day content calendar, social media post templates (Instagram, TikTok, Snapchat), email sequences, SMS templates, landing page wireframes, ad creative briefs, and a post-campaign analytics report template. Arabic-first with English translations.","ar":"يتضمن تقويم محتوى لـ ٣٠ يوماً، قوالب منشورات التواصل الاجتماعي (إنستقرام، تيك توك، سناب شات)، سلاسل بريد، قوالب SMS، مخططات صفحات الهبوط، موجزات إبداع إعلاني، وقالب تقرير تحليلات ما بعد الحملة. عربي أولاً مع ترجمات إنجليزية."}','[{"en":"30-day content calendar","ar":"تقويم محتوى ٣٠ يوماً"},{"en":"Social templates (IG/TikTok/Snap)","ar":"قوالب سوشل (IG/TikTok/Snap)"},{"en":"Email + SMS sequences","ar":"سلاسل بريد + SMS"},{"en":"Landing page wireframes","ar":"مخططات صفحات الهبوط"},{"en":"Post-campaign analytics template","ar":"قالب تحليلات ما بعد الحملة"}]','',3499,5499,'USD', ARRAY['en','ar'],'commercial_use',5,true,156,4.83,26,now()),
  ('p0000022-0000-0000-0000-000000000022','saas-pricing-playbook','c4444444-4444-4444-4444-444444444444','pdf','published','{"en":"SaaS Pricing Playbook","ar":"دليل تسعير SaaS"}','{"en":"Data-driven pricing strategies for MENA SaaS founders.","ar":"استراتيجيات تسعير مدفوعة بالبيانات لمؤسسي SaaS في منطقة الشرق الأوسط وشمال إفريقيا."}','{"en":"Covers pricing psychology, tier design, freemium vs trial, regional payment preferences (STCPay, Apple Pay, Tamara), benchmark data from 50+ MENA SaaS companies, and a pricing calculator spreadsheet. Written for founders selling to SMBs and enterprises in the Gulf.","ar":"يغطي علم نفس التسعير، تصميم المستويات، freemium مقابل trial، تفضيلات الدفع الإقليمية (STC Pay، Apple Pay، تمارا)، بيانات معيارية من ٥٠+ شركة SaaS في المنطقة، وجدول حساب التسعير. مكتوب لمؤسسين يبيعون للشركات الصغيرة والمتوسطة والمؤسسات في الخليج."}','[{"en":"Pricing psychology frameworks","ar":"إطارات علم نفس التسعير"},{"en":"MENA payment preferences","ar":"تفضيلات الدفع في الشرق الأوسط"},{"en":"Benchmark data (50+ companies)","ar":"بيانات معيارية (٥٠+ شركة)"},{"en":"Pricing calculator spreadsheet","ar":"جدول حساب التسعير"},{"en":"Tier design + packaging","ar":"تصميم المستويات + التغليف"}]','',2499,3999,'USD', ARRAY['en','ar'],'commercial_use',5,false,63,4.58,12,now()),
  ('p0000023-0000-0000-0000-000000000023','product-manager-notion-os','c6666666-6666-6666-6666-666666666666','notion','published','{"en":"Product Manager OS — Notion","ar":"نظام مدير المنتج — Notion"}','{"en":"Run your entire product lifecycle inside Notion.","ar":"أدر دورة حياة منتجك بالكامل داخل Notion."}','{"en":"Includes roadmap tracker, OKR dashboard, user research database, feature request pipeline, sprint planning board, release notes template, stakeholder communication log, and analytics review hub. Designed for product teams in fast-growing startups.","ar":"يتضمن متتبع خارطة الطريق، لوحة OKR، قاعدة بيانات أبحاث المستخدم، مجرى طلبات الميزات، لوحة تخطيط السبرينت، قالب ملاحظات الإصدار، سجل التواصل مع أصحاب المصلحة، ومركز مراجعة التحليلات. مصمم لفرق المنتج في الشركات الناشئة سريعة النمو."}','[{"en":"Roadmap + OKR dashboard","ar":"خارطة الطريق + لوحة OKR"},{"en":"User research database","ar":"قاعدة بيانات أبحاث المستخدم"},{"en":"Feature request pipeline","ar":"مجرى طلبات الميزات"},{"en":"Sprint planning board","ar":"لوحة تخطيط السبرينت"},{"en":"Release notes + stakeholder log","ar":"ملاحظات الإصدار + سجل أصحاب المصلحة"}]','',2999,4999,'USD', ARRAY['en','ar'],'commercial_use',5,false,98,4.77,18,now()),
  ('p0000024-0000-0000-0000-000000000024','arabic-ui-ux-checklist','c1111111-1111-1111-1111-111111111111','template','published','{"en":"Arabic UI/UX Checklist","ar":"قائمة مراجعة UI/UX العربية"}','{"en":"200-point checklist for designing Arabic-first interfaces.","ar":"قائمة مراجعة ٢٠٠ نقطة لتصميم واجهات عربية أولاً."}','{"en":"Covers RTL layout, font pairing, text expansion, number formatting, date localization, form validation messages, error states, accessibility (WCAG 2.1 AA), color contrast for Arabic scripts, and cultural UX considerations. Used by designers at Careem, Talabat, and Noon.","ar":"يغطي تخطيط RTL، أزواج الخطوط، توسيع النص، تنسيق الأرقام، توطين التاريخ، رسائل التحقق من النماذج، حالات الخطأ، إمكانية الوصول (WCAG 2.1 AA)، تباين الألوان للخطوط العربية، واعتبارات UX الثقافية. يستخدمها مصممون في Careem وTalabat وNoon."}','[{"en":"200 checkpoints","ar":"٢٠٠ نقطة مراجعة"},{"en":"RTL + font + text expansion","ar":"RTL + خط + توسيع النص"},{"en":"WCAG 2.1 AA compliance","ar":"امتثال WCAG 2.1 AA"},{"en":"Cultural UX considerations","ar":"اعتبارات UX الثقافية"},{"en":"Used by Careem, Talabat, Noon","ar":"مستخدم من Careem و Talabat و Noon"}]','',1499,2499,'USD', ARRAY['en','ar'],'commercial_use',5,false,45,4.69,8,now()),
  ('p0000025-0000-0000-0000-000000000025','growth-hacking-mini-course','c7777777-7777-7777-7777-777777777777','course','published','{"en":"Growth Hacking Mini-Course","ar":"كورس Growth Hacking المصغر"}','{"en":"72-minute video course on acquisition, activation, retention, and monetization for Arabic startups.","ar":"كورس فيديو ٧٢ دقيقة حول الاستحواذ، التفعيل، الاستبقاء، والتحويل للشركات الناشئة العربية."}','{"en":"Taught by a growth lead who scaled two UAE startups from 0 to 50K users. Covers TikTok organic growth, WhatsApp community building, referral loops, landing page optimization, and paid ad arbitrage for GCC markets. Includes slide deck and action worksheet.","ar":"مقدم من قِبل رئيس نمو قاسم شركتين في الإمارات من ٠ إلى ٥٠ ألف مستخدم. يغطي النمو العضوي على TikTok، بناء مجتمع WhatsApp، حلقات الإحالة، تحسين صفحات الهبوط، والمراجحة الإعلانية المدفوعة لأسواق الخليج. يتضمن عرض الشرائح وورقة عمل."}','[{"en":"72-minute HD video","ar":"فيديو ٧٢ دقيقة HD"},{"en":"TikTok + WhatsApp growth","ar":"نمو TikTok + WhatsApp"},{"en":"Landing page optimization","ar":"تحسين صفحات الهبوط"},{"en":"Paid ad arbitrage (GCC)","ar":"مراجحة الإعلانات المدفوعة (GCC)"},{"en":"Slide deck + worksheet","ar":"عرض شرائح + ورقة عمل"}]','',3999,5999,'USD', ARRAY['en','ar'],'personal_use',5,true,234,4.86,37,now());

-- ----- product_files: add a dummy file for each product so downloads work ----
insert into product_files (id, product_id, filename, storage_path, size_bytes, mime)
select
  gen_random_uuid(),
  id,
  title->>'en' || '.zip',
  '/uploads/products/' || slug || '.zip',
  (floor(random()*50)::int + 1) * 1024 * 1024,
  'application/zip'
from products;

-- Done
